### ISSUE TITLE
Amélioration Evenements

### ISSUE THREAD

**Issue by paul92ilm** [Minishlink/physbook#123]
Possibilité d'ajouter un fichier pour plus de détails
Possibilité de choisir le nombre maximum de participants
Augmentation du champ de description pour plus de précision

Suggestion de Skialadz 167

**Comment by paul92ilm** [comment]
Création de groupes personnalisés

Suggestion de S'h 1-136

**Comment by batgau71** [comment]
* Possibilité d'ajouter manuellement des PGs post-manip s'ils ont oublié de se bucquer (par harpag's seulement)
* Définir un horaire à partir duquel il n'est plus possible de se bucquer (mais l’événement reste toujours visible)
* Possibilité de se bucquer plusieurs fois (ex : double bucquage à la restal car je prend du rab')

**Comment by Minishlink** [comment]
Pour "Possibilité d'ajouter un fichier pour plus de détails" : je trouve pas ça fou fou. Un lien vers un Google Drive semble une meilleure solution : ça revient au même sauf que sur Google Drive le fichier pourra être plus gros et sous n'importe quel format."

Pour "Augmentation du champ de description pour plus de précision" : là j'avoue ne pas comprendre, il utilise quoi comme navigateur ? Parce que normalement tous les navigateurs récents permettent d'agrandir le champ. Et de toute façon que le champ soit petit n'empêche pas d'écrire beaucoup dedans... Faudrait ptet le tuisser...

Ces deux suggestions se rejoignent dans le sens où l'utilisateur veut pouvoir mettre plus d'infos. Mais quelles infos ? Sous quelle forme ? Si quelqu'un peut lui demander un exemple...

**Comment by paul92ilm** [comment]
J'en ai parlé avec Skialadz et il m'a donné l'exemple d'une fiche manip
