### ISSUE TITLE
Export des comptes

### ISSUE THREAD

**Issue by astridfrot** [Minishlink/physbook#132]
Impossibilité d'exporter les comptes avec le bouton Export
Pb apparaissant sur chacune des interfaces de gestion 

Description du bug: lorsqu'on clique sur export, la page charge puis l'interface de gestion réapparait sans fichier téléchargé. 

Export des comptes par copier/coller sur excel fonctionne

**Comment by Minishlink** [comment]
Quel navigateur ?

Cela fonctionne bien chez moi.

**Comment by Minishlink** [comment]
L'erreur était due à la sélection d'une date qui n'existait pas. (31 novembre 2015)
