### ISSUE TITLE
Performance in Encryption::encrypt

### ISSUE THREAD

**Issue by cap-mayank** [Minishlink/physbook#142]
HI,
Thanks for Minishlink it work well for me for limited user's.

I am facing performance and high CPU uses issue when I try API for around 1500 users token. API taking around 1 hours to send notification to 1500 users. I tried to debug the code and go t to know that. the issue is in WebPush.php file at line number 191 Encryption::encrypt();

Can you please suggest any clue to solve this. I am happy to resolve this issue and commit code here as well.

Thanks,
Mayank Kanungo

**Comment by Minishlink** [comment]
Hi @cap-mayank, I believe this is an issue for my WebPush library? I'm happy to answer on the corresponding repo ;)
