### ISSUE TITLE
Trier par num's

### ISSUE THREAD

**Issue by Minishlink** [Minishlink/physbook#28]
Originally reported by: **Louis Lagrange (BitBucket: [louis_lagrange](http://bitbucket.org/louis_lagrange), GitHub: [louis_lagrange](http://github.com/louis_lagrange))**

----------------------------------------

Au lieu de prendre la fam's complète, juste prendre le premier num's histoire d'avoir un tri correct. (avec la fam's cela trie comme une chaine de caractères)

----------------------------------------
- Bitbucket: https://bitbucket.org/louis_lagrange/physbook/issue/16

**Comment by Minishlink** [comment]
Il faut implémenter un parser de fam's et attribuer un ordre selon la première fam's.

**Comment by batgau71** [comment]
:+1:
