### ISSUE TITLE
Faire la font des icones monochromes

### ISSUE THREAD

**Issue by Minishlink** [Minishlink/physbook#31]
Originally reported by: **Louis Lagrange (BitBucket: [louis_lagrange](http://bitbucket.org/louis_lagrange), GitHub: [louis_lagrange](http://github.com/louis_lagrange))**

----------------------------------------

Pour rendre plus léger le site.

----------------------------------------
Bitbucket: https://bitbucket.org/louis_lagrange/physbook/issue/19

- [x] Créer la fonte (6)
- [ ] L'intégrer au site (2)

**Comment by Minishlink** [comment]
Sol&'i a normalement fini la fonte, il faut bien l'intégrer au site et s'assurer que la dernière version est sur le Drive

**Comment by paul92ilm** [comment]
Récupérer la fonte à Soleil
