### ISSUE TITLE
Recensement des boquettes

### ISSUE THREAD

**Issue by Minishlink** [Minishlink/physbook#49]
Originally reported by: **Louis Lagrange (BitBucket: [louis_lagrange](http://bitbucket.org/louis_lagrange), GitHub: [louis_lagrange](http://github.com/louis_lagrange))**

----------------------------------------

Liste des boquettes
Logos si possible
Liste des responsabilités
Liste des responsables

----------------------------------------
- Bitbucket: https://bitbucket.org/louis_lagrange/physbook/issue/39

**Comment by Minishlink** [comment]
Demander à Stéphie et Alice où elles en étaient et si tout est rentré Phy'sbook.

**Comment by paul92ilm** [comment]
Sur Phy'sbook il y a très peu de boquettes, il manque par exemple toutes les boquettes de sport. Et des boquettes genre Airsoft, Gadz&Furious etc.. On est bien d'accord qu'on les met toutes ?

**Comment by Minishlink** [comment]
Oui, toutes ! :) (même les moins actives de façon à avoir un historique)

**Comment by paul92ilm** [comment]
Toutes les responsabilités ont été crées
Tous les Zi de Sport ont été ajoutés

**Comment by paul92ilm** [comment]
[Boquettes Restantes.xlsx](https://github.com/Minishlink/physbook/files/18575/Boquettes.Restantes.xlsx)

**Comment by Ilton3** [comment]
[Boquettes.Restantes.xlsx | uploaded via ZenHub](https://files.zenhub.io/562901a30cf88dac1d15efb2)

Mis à jour, on est presque bon (manque A&V, et quelques autres)
