### ISSUE TITLE
Finir évènements

### ISSUE THREAD

**Issue by Minishlink** [Minishlink/physbook#67]
- [x] Nettoyage du code
- [x] Info coût + rechargement de compte
- [x] Évènement majeur/mineur
- [x] Redirection après création
- [x] Info paiement effectué
- [x] Déclenchement paiement
- [x] Synchro R&z@l
- [x] Affichage historique Pi
- [x] Notifications modification/suppression/invitation
- [x] Export Excel présence

**Comment by batgau71** [comment]
Es-tu toujours déçu ?

**Comment by Minishlink** [comment]
Oui.

**Comment by Ilton3** [comment]
Pour le moment, le logo des événements (pour la page qui n'est pas encore fonctionnelle) est lié aux fin'ss. Ca ne serait pas mieux de faire un logo plus général pour tous les types d’événement (soirées etc...)?

**Comment by Minishlink** [comment]
Au départ les fins devaient être un truc à part des événements (c'était la distinction majeur/mineur en fait). Du coup maintenant cette icône n'a plus lieu d'être oui, et on pourrait la remplacer par un agenda par exemple.
