### ISSUE TITLE
Création d'un Type de formulaire personnalisé

### ISSUE THREAD

**Issue by paul92ilm** [Minishlink/physbook#75]
Création de PJMType implémentant la variable 'help_label'
Remplacement de AbstractType par PJMType

**Comment by paul92ilm** [comment]
http://symfony.com/fr/doc/current/cookbook/form/create_custom_field_type.html

**Comment by Minishlink** [comment]
Tu peux aussi t'aider des types personnalisés que j'ai déjà créé. :)

**Comment by paul92ilm** [comment]
Réalisation avec l'issue #71
