### ISSUE TITLE
[Web App] [Safari] Redirections

### ISSUE THREAD

**Issue by ptwom** [Minishlink/physbook#76]
Problèmes de redirection sur le navigateur quand on clique sur certaines fonctions via la Web App
Ex : Annuaire, visualiser les infos de (Fon)^2 => La web app switch pour le navigateur (en l'occurence Safari pour moi) et donc on doit se reconnecter pour après accéder au profil de (Fon)^2.

**Comment by ptwom** [comment]
D'ailleurs, dès qu'on passe la Web App en background sur iPhone, on doit se reconnecter quand on y retourne, malgré "se souvenir de moi"

**Comment by Minishlink** [comment]
Ca vient bien de Safari dans les deux cas.

J'avais déjà essayé de faire un fix pour la première chose dont tu me parles (vers la ligne 6 de [nav.js](https://github.com/Minishlink/physbook/blob/5ba412deaaaa82c25ac5b455b65d2aacadee3541/app/Resources/public/js/nav.js)), apparemment ça ne suffit pas.

Pour le deuxième problème, c'est un problème inhérent à iOS et pas corrigeable.

**Comment by Minishlink** [comment]
Corrigé dans les nouvelles versions de Safari.
