### ISSUE TITLE
[Pian'ss] Planning dérunssage

### ISSUE THREAD

**Issue by Ilton3** [Minishlink/physbook#92]
Les ZiPi souhaiteraient pouvoir ajouter leur planning de dérunssage à la page Pian'ss. Ils se moquent du format (excel, image, physbook direct) mais aimeraient que se soit visible le plus tôt possible

**Comment by Minishlink** [comment]
Événements ! Ils en créent un pour chaque drunssage en invitant que les gens concernés via le filtre associé et en précisant le lieu "Pian's".

Pour l'instant ça sera affiché que dans les événements, mais des que #89 est fini, ça sera le cas aussi sur la page du pian's.

**Comment by astridfrot** [comment]
Le planning de drunssage sera sous la forme d'une image pimpée style Phy'sbook sous forme de tableau.
Ce sera la version 1, à améliorer plus tard.

**Comment by paul92ilm** [comment]
La version 2 sera comme sur la plaquette en ajoutant le demi cool's concerné..
