### ISSUE TITLE
[Pian'ss] Liste HPi

### ISSUE THREAD

**Issue by Ilton3** [Minishlink/physbook#93]
Afficher la liste des HPi sur la page du Pian'ss pour avoir plus de visibilité sur les mises HPi et les faire mieux respecter.

**Comment by Minishlink** [comment]
Pour ça il va falloir définir HPi, est ce que ce sont tous les gens en dessous d'une telle somme ou bien les ZiPi ont-ils un droit de regard ?

En fonction, il faudra créer un attribut type HPi ("frozen") pour les comptes et faire l'interface qu'il faut sur la page de gestion, ainsi que la synchronisation avec le serveur du Rezal.

**Comment by Ilton3** [comment]
Les HPi sont tous les gens à -30€ et plus. Ca a été fixé hier en réun'ss avec l'Asso.

**Comment by Minishlink** [comment]
Cool ! Du coup rien à changer côté MDD.

**Comment by Minishlink** [comment]
Considérez que c'est fait côté code, donc là il manque juste la présentation des noms HPi, on fait quoi comme design et on le place où sur la page ?

Pour vous lancer, je propose de mettre le calendrier en bas à gauche, les HPi en bas au milieu et les ZiPi en bas à droite.
