### ISSUE TITLE
Affiche Amphi conscrits 

### ISSUE THREAD

**Issue by astridfrot** [Minishlink/physbook#95]
Faire une affiche pour l'amphi de présentation de phy'sbook aux conscrits type amphi mystère

**Comment by paul92ilm** [comment]
![affiche puntos 2](https://cloud.githubusercontent.com/assets/9373163/10017307/8bdec258-612d-11e5-9bdb-a030326e18f2.jpg)

**Comment by paul92ilm** [comment]
Version sans trait blanc sur le drive, date et lieu à adapter

**Comment by paul92ilm** [comment]
En attente de l'amphi Pian's
