### ISSUE TITLE
PowerPoint de présentation amphi conscrits 

### ISSUE THREAD

**Issue by astridfrot** [Minishlink/physbook#97]
Powerpoint à base d'un visuel photoshop 
Plan: 
1/ Pourquoi Phy'sbook ?
2/ Les principales fonctionnalités (Pi,Brag's,Annuaire...)

(Démo en direct)

3/ Conclusion (Phy'sbook c'est aussi...,HM Phy'sbook ?)

**Comment by ptwom** [comment]
+ le phy'ss
